import type { Track } from '../types';

/**
 * Additional aartis, mantras and bhajans across the pantheon, so the library,
 * journeys and deity pages have real material. Same rules as the core seed:
 * `audio` is null (follow-along), text is traditional/public-domain, and
 * translations are plain-English renderings pending scholarly review.
 */
export const EXTRA_TRACKS: Track[] = [
  {
    id: 'jai-ganesh-deva',
    title: 'Jai Ganesh Deva',
    devanagari: 'जय गणेश देवा',
    kind: 'aarti',
    deityId: 'ganesha',
    language: 'hi',
    artist: 'Traditional',
    duration: 48,
    audio: null,
    isFree: true,
    previewSeconds: 30,
    attribution: 'Traditional aarti · public domain',
    tags: ['aarti', 'beginnings', 'wednesday'],
    lyrics: [
      { t: 0, section: 'Refrain', devanagari: 'जय गणेश जय गणेश जय गणेश देवा।', transliteration: 'jaya gaṇesha jaya gaṇesha jaya gaṇesha devā', translation: 'Victory to Lord Ganesha, again and again.' },
      { t: 10, section: 'Refrain', devanagari: 'माता जाकी पार्वती पिता महादेवा॥', transliteration: 'mātā jākī pārvatī pitā mahādevā', translation: 'Whose mother is Parvati and whose father is Mahadeva.' },
      { t: 22, devanagari: 'एकदंत दयावंत चार भुजाधारी।', transliteration: 'ekadanta dayāvanta chāra bhujā dhārī', translation: 'Single-tusked and compassionate, bearing four arms,' },
      { t: 34, devanagari: 'माथे सिंदूर सोहे मूसे की सवारी॥', transliteration: 'māthe sindūra sohe mūse kī savārī', translation: 'vermilion gracing your brow, riding upon the mouse.' },
    ],
  },
  {
    id: 'om-jai-lakshmi-mata',
    title: 'Om Jai Lakshmi Mata',
    devanagari: 'ॐ जय लक्ष्मी माता',
    kind: 'aarti',
    deityId: 'lakshmi',
    language: 'hi',
    artist: 'Traditional',
    duration: 44,
    audio: null,
    isFree: true,
    attribution: 'Traditional aarti · public domain',
    tags: ['aarti', 'friday', 'abundance', 'diwali'],
    lyrics: [
      { t: 0, section: 'Refrain', devanagari: 'ॐ जय लक्ष्मी माता, मैया जय लक्ष्मी माता।', transliteration: 'oṁ jaya lakshmī mātā, maiyā jaya lakshmī mātā', translation: 'Om, victory to Mother Lakshmi, hail to you, Mother.' },
      { t: 12, section: 'Refrain', devanagari: 'तुमको निशदिन सेवत, हर विष्णु विधाता॥', transliteration: 'tumako niśadina sevata, hara vishṇu vidhātā', translation: 'Shiva, Vishnu and Brahma serve you day and night.' },
      { t: 26, devanagari: 'उमा रमा ब्रह्माणी, तुम ही जग माता।', transliteration: 'umā ramā brahmāṇī, tuma hī jaga mātā', translation: 'As Uma, Rama and Brahmani, you are the mother of the world.' },
      { t: 36, devanagari: 'सूर्य चंद्रमा ध्यावत, नारद ऋषि गाता॥', transliteration: 'sūrya chandramā dhyāvata, nārada ṛṣi gātā', translation: 'The sun and moon meditate on you; sage Narada sings your praise.' },
    ],
  },
  {
    id: 'ambe-tu-hai-jagdambe',
    title: 'Ambe Tu Hai Jagdambe',
    devanagari: 'अम्बे तू है जगदम्बे',
    kind: 'aarti',
    deityId: 'durga',
    language: 'hi',
    artist: 'Traditional',
    duration: 46,
    audio: null,
    isFree: true,
    attribution: 'Traditional aarti · public domain',
    tags: ['aarti', 'navratri', 'shakti'],
    lyrics: [
      { t: 0, section: 'Refrain', devanagari: 'अम्बे तू है जगदम्बे काली, जय दुर्गे खप्पर वाली।', transliteration: 'ambe tū hai jagadambe kālī, jaya durge khappara vālī', translation: 'O Amba, you are the Mother of the world, Kali; victory to Durga who bears the bowl.' },
      { t: 14, section: 'Refrain', devanagari: 'तेरे ही गुण गावें भारती, ओ मैया हम सब उतारें आरती॥', transliteration: 'tere hī guṇa gāven bhāratī, o maiyā hama saba utāren āratī', translation: 'We sing only your glories, Mother, and offer this aarti to you.' },
      { t: 30, devanagari: 'तेरे भक्त जनों पर माता, भीर पड़ी है भारी।', transliteration: 'tere bhakta janon para mātā, bhīra paṛī hai bhārī', translation: 'O Mother, when great trouble falls upon your devotees,' },
      { t: 40, devanagari: 'दानव दल पर टूट पड़ो माँ, करके सिंह सवारी॥', transliteration: 'dānava dala para ṭūṭa paṛo māṁ, karake siṁha savārī', translation: 'fall upon the hordes of demons, riding your lion.' },
    ],
  },
  {
    id: 'om-jai-shiv-omkara',
    title: 'Om Jai Shiv Omkara',
    devanagari: 'ॐ जय शिव ओंकारा',
    kind: 'aarti',
    deityId: 'shiva',
    language: 'hi',
    artist: 'Traditional',
    duration: 42,
    audio: null,
    isFree: false,
    previewSeconds: 25,
    attribution: 'Traditional aarti · public domain',
    tags: ['aarti', 'monday', 'shivaratri'],
    lyrics: [
      { t: 0, section: 'Refrain', devanagari: 'ॐ जय शिव ओंकारा, स्वामी जय शिव ओंकारा।', transliteration: 'oṁ jaya śiva oṁkārā, swāmī jaya śiva oṁkārā', translation: 'Om, victory to Shiva, the primordial sound Omkara.' },
      { t: 12, section: 'Refrain', devanagari: 'ब्रह्मा विष्णु सदाशिव, अर्द्धांगी धारा॥', transliteration: 'brahmā vishṇu sadāśiva, arddhāṅgī dhārā', translation: 'Brahma, Vishnu and eternal Shiva — you hold the half-feminine form.' },
      { t: 26, devanagari: 'एकानन चतुरानन पञ्चानन राजे।', transliteration: 'ekānana chaturānana pañchānana rāje', translation: 'One-faced, four-faced and five-faced, you reign,' },
      { t: 34, devanagari: 'हंसासन गरुड़ासन वृषवाहन साजे॥', transliteration: 'haṁsāsana garuḍāsana vṛṣavāhana sāje', translation: 'adorned on swan, eagle and the bull as your mount.' },
    ],
  },
  {
    id: 'saraswati-vandana',
    title: 'Saraswati Vandana',
    devanagari: 'सरस्वती वंदना',
    kind: 'stotra',
    deityId: 'saraswati',
    language: 'sa',
    artist: 'Traditional',
    duration: 36,
    audio: null,
    isFree: false,
    previewSeconds: 20,
    attribution: 'Traditional dhyana shloka · public domain',
    tags: ['knowledge', 'students', 'vasant-panchami'],
    lyrics: [
      { t: 0, devanagari: 'या कुन्देन्दुतुषारहारधवला या शुभ्रवस्त्रावृता।', transliteration: 'yā kundendu-tuṣāra-hāra-dhavalā yā śubhra-vastrāvṛtā', translation: 'She who is white as jasmine, the moon and snow, robed in pure white,' },
      { t: 12, devanagari: 'या वीणावरदण्डमण्डितकरा या श्वेतपद्मासना॥', transliteration: 'yā vīṇā-vara-daṇḍa-maṇḍita-karā yā śveta-padmāsanā', translation: 'whose hands are graced by the veena, seated upon the white lotus —' },
      { t: 24, devanagari: 'सा मां पातु सरस्वती भगवती निःशेषजाड्यापहा॥', transliteration: 'sā māṁ pātu sarasvatī bhagavatī niḥśeṣa-jāḍyāpahā', translation: 'may that Goddess Saraswati, remover of all dullness, protect me.' },
    ],
  },
  {
    id: 'govind-bolo',
    title: 'Govind Bolo Hari Gopal Bolo',
    devanagari: 'गोविन्द बोलो',
    kind: 'bhajan',
    deityId: 'krishna',
    language: 'hi',
    artist: 'Traditional',
    duration: 40,
    audio: null,
    isFree: true,
    attribution: 'Traditional bhajan · public domain',
    tags: ['kirtan', 'joy', 'janmashtami'],
    lyrics: [
      { t: 0, devanagari: 'गोविन्द बोलो हरि गोपाल बोलो।', transliteration: 'govinda bolo hari gopāla bolo', translation: 'Sing the names: Govinda, Hari, Gopala!' },
      { t: 12, devanagari: 'राधा रमण हरि गोविन्द बोलो॥', transliteration: 'rādhā ramaṇa hari govinda bolo', translation: 'Beloved of Radha, Hari — sing Govinda!' },
      { t: 24, devanagari: 'गोविन्द बोलो हरि गोपाल बोलो।', transliteration: 'govinda bolo hari gopāla bolo', translation: 'Sing the names: Govinda, Hari, Gopala!' },
    ],
  },
];
