import type { Track } from '../types';

/**
 * Devotional audio tracks with time-synced lyrics.
 *
 * IMPORTANT: `audio` is null for every seed track — Diya does not ship
 * copyrighted recordings. The player renders the synced-lyric experience using
 * the `t` timings (a paced "follow-along" scroll) so the flagship feature is
 * fully demonstrable. In production, set `audio` to a licensed/commissioned
 * recording (remote CDN uri or bundled require) and keep the same timings.
 *
 * Text is traditional/public-domain. Transliteration is phonetic (IAST-leaning)
 * and translations are faithful plain-English renderings authored for Diya.
 * Flag all sacred text for scholarly verification before production.
 */

const hanumanChalisa: Track = {
  id: 'hanuman-chalisa',
  title: 'Hanuman Chalisa',
  devanagari: 'हनुमान चालीसा',
  kind: 'chalisa',
  deityId: 'hanuman',
  language: 'hi',
  artist: 'Traditional · Tulsidas',
  duration: 368,
  audio: null,
  isFree: true,
  previewSeconds: 60,
  attribution: 'Goswami Tulsidas (16th c.) · public domain',
  tags: ['tuesday', 'saturday', 'strength', 'protection'],
  lyrics: [
    {
      t: 0,
      section: 'Doha',
      devanagari: 'श्रीगुरु चरन सरोज रज, निज मनु मुकुरु सुधारि।',
      transliteration: 'shrī guru charana saroja raja, nija manu mukuru sudhāri',
      translation:
        "Cleansing the mirror of my mind with the dust of my Guru's lotus feet,",
    },
    {
      t: 8,
      section: 'Doha',
      devanagari: 'बरनउँ रघुबर बिमल जसु, जो दायकु फल चारि॥',
      transliteration: 'baranau raghubara bimala jasu, jo dāyaku phala chāri',
      translation: 'I sing the pure glory of Sri Rama, who bestows the four fruits of life.',
    },
    {
      t: 16,
      section: 'Doha',
      devanagari: 'बुद्धिहीन तनु जानिके, सुमिरौं पवनकुमार।',
      transliteration: 'buddhihīna tanu jānike, sumirau pavana-kumāra',
      translation: 'Knowing my body to be devoid of wit, I remember you, son of the Wind.',
    },
    {
      t: 24,
      section: 'Doha',
      devanagari: 'बल बुधि बिद्या देहु मोहिं, हरहु कलेस बिकार॥',
      transliteration: 'bala budhi bidyā dehu mohi, harahu kalesa bikāra',
      translation: 'Grant me strength, wisdom and knowledge, and remove my afflictions.',
    },
    {
      t: 32,
      section: 'Chaupai',
      devanagari: 'जय हनुमान ज्ञान गुन सागर। जय कपीस तिहुँ लोक उजागर॥',
      transliteration: 'jaya hanumāna jñāna guna sāgara, jaya kapīsa tihu loka ujāgara',
      translation:
        'Victory to Hanuman, ocean of wisdom and virtue; victory to the lord of vanaras who lights the three worlds.',
    },
    {
      t: 40,
      section: 'Chaupai',
      devanagari: 'राम दूत अतुलित बल धामा। अंजनि पुत्र पवनसुत नामा॥',
      transliteration: 'rāma dūta atulita bala dhāmā, anjani putra pavanasuta nāmā',
      translation:
        'Messenger of Rama, abode of matchless strength, known as son of Anjani and child of the Wind.',
    },
    {
      t: 48,
      section: 'Chaupai',
      devanagari: 'महाबीर बिक्रम बजरंगी। कुमति निवार सुमति के संगी॥',
      transliteration: 'mahābīra bikrama bajarangī, kumati nivāra sumati ke sangī',
      translation:
        'Great hero, mighty as a thunderbolt, remover of base thoughts and companion of the wise.',
    },
    {
      t: 56,
      section: 'Chaupai',
      devanagari: 'कंचन बरन बिराज सुबेसा। कानन कुंडल कुंचित केसा॥',
      transliteration: 'kanchana barana birāja subesā, kānana kundala kunchita kesā',
      translation: 'Golden-hued and beautifully adorned, with rings in your ears and curling hair.',
    },
    {
      t: 64,
      section: 'Chaupai',
      devanagari: 'हाथ बज्र औ ध्वजा बिराजै। काँधे मूँज जनेऊ साजै॥',
      transliteration: 'hātha bajra au dhvajā birājai, kāndhe mūnja janeū sājai',
      translation: 'In your hands shine mace and banner; a sacred thread graces your shoulder.',
    },
    {
      t: 72,
      section: 'Chaupai',
      devanagari: 'शंकर सुवन केसरी नंदन। तेज प्रताप महा जग बंदन॥',
      transliteration: 'shankara suvana kesarī nandana, teja pratāpa mahā jaga bandana',
      translation: "Portion of Shiva, delight of Kesari; your splendor is revered by all the world.",
    },
    {
      t: 80,
      section: 'Chaupai',
      devanagari: 'विद्यावान गुनी अति चातुर। राम काज करिबे को आतुर॥',
      transliteration: 'vidyāvāna gunī ati chātura, rāma kāja karibe ko ātura',
      translation: 'Learned, virtuous and exceedingly clever, ever eager to do the work of Rama.',
    },
    {
      t: 88,
      section: 'Chaupai',
      devanagari: 'प्रभु चरित्र सुनिबे को रसिया। राम लखन सीता मन बसिया॥',
      transliteration: 'prabhu charitra sunibe ko rasiyā, rāma lakhana sītā mana basiyā',
      translation:
        "You delight in the Lord's story; Rama, Lakshmana and Sita dwell within your heart.",
    },
    {
      t: 96,
      section: 'Chaupai',
      devanagari: 'सूक्ष्म रूप धरि सियहिं दिखावा। बिकट रूप धरि लंक जरावा॥',
      transliteration: 'sūkshma rūpa dhari siyahi dikhāvā, bikata rūpa dhari lanka jarāvā',
      translation: 'In tiny form you appeared before Sita; in fearsome form you burned Lanka.',
    },
    {
      t: 104,
      section: 'Chaupai',
      devanagari: 'भीम रूप धरि असुर सँहारे। रामचंद्र के काज सँवारे॥',
      transliteration: 'bhīma rūpa dhari asura sanhāre, rāmachandra ke kāja sanvāre',
      translation: "In mighty form you slew the demons and set right Sri Rama's tasks.",
    },
    {
      t: 112,
      section: 'Chaupai',
      devanagari: 'लाय सजीवन लखन जियाये। श्रीरघुबीर हरषि उर लाये॥',
      transliteration: 'lāya sajīvana lakhana jiyāye, shrī raghubīra harashi ura lāye',
      translation: 'You brought the sanjivani herb and revived Lakshmana; Sri Rama joyfully embraced you.',
    },
    {
      t: 120,
      section: 'Chaupai',
      devanagari: 'रघुपति कीन्ही बहुत बड़ाई। तुम मम प्रिय भरतहि सम भाई॥',
      transliteration: 'raghupati kīnhī bahuta baṛāī, tuma mama priya bharatahi sama bhāī',
      translation: 'Rama praised you greatly, calling you as dear to him as his brother Bharata.',
    },
    {
      t: 128,
      section: 'Chaupai',
      devanagari: 'सहस बदन तुम्हरो जस गावैं। अस कहि श्रीपति कंठ लगावैं॥',
      transliteration: 'sahasa badana tumharo jasa gāvain, asa kahi shrīpati kantha lagāvain',
      translation: 'A thousand mouths sing your glory — so saying, the Lord drew you to his heart.',
    },
    {
      t: 136,
      section: 'Chaupai',
      devanagari: 'सनकादिक ब्रह्मादि मुनीसा। नारद सारद सहित अहीसा॥',
      transliteration: 'sanakādika brahmādi munīsā, nārada sārada sahita ahīsā',
      translation: 'Sanaka and the sages, Brahma and the great seers, Narada, Saraswati and Sheshnag,',
    },
    {
      t: 144,
      section: 'Chaupai',
      devanagari: 'जम कुबेर दिगपाल जहाँ ते। कबि कोबिद कहि सके कहाँ ते॥',
      transliteration: 'jama kubera digapāla jahā te, kabi kobida kahi sake kahā te',
      translation: 'Yama, Kubera and the guardians of the directions — what poet or scholar can tell your full glory?',
    },
    {
      t: 152,
      section: 'Chaupai',
      devanagari: 'तुम उपकार सुग्रीवहिं कीन्हा। राम मिलाय राज पद दीन्हा॥',
      transliteration: 'tuma upakāra sugrīvahi kīnhā, rāma milāya rāja pada dīnhā',
      translation: 'You did Sugriva a great kindness, uniting him with Rama and restoring his throne.',
    },
    {
      t: 160,
      section: 'Chaupai',
      devanagari: 'तुम्हरो मंत्र बिभीषन माना। लंकेश्वर भए सब जग जाना॥',
      transliteration: 'tumharo mantra bibhīshana mānā, lankeshvara bhaye saba jaga jānā',
      translation: 'Vibhishana heeded your counsel and became lord of Lanka, as all the world knows.',
    },
    {
      t: 168,
      section: 'Chaupai',
      devanagari: 'जुग सहस्र जोजन पर भानू। लील्यो ताहि मधुर फल जानू॥',
      transliteration: 'juga sahasra jojana para bhānū, līlyo tāhi madhura phala jānū',
      translation: 'The sun, thousands of yojanas away, you swallowed, mistaking it for a sweet fruit.',
    },
    {
      t: 176,
      section: 'Chaupai',
      devanagari: 'प्रभु मुद्रिका मेलि मुख माहीं। जलधि लाँघि गये अचरज नाहीं॥',
      transliteration: 'prabhu mudrikā meli mukha māhī, jaladhi lāghi gaye acharaja nāhī',
      translation: "Holding the Lord's ring in your mouth, you leapt across the ocean — no wonder at all.",
    },
    {
      t: 184,
      section: 'Chaupai',
      devanagari: 'दुर्गम काज जगत के जेते। सुगम अनुग्रह तुम्हरे तेते॥',
      transliteration: 'durgama kāja jagata ke jete, sugama anugraha tumhare tete',
      translation: 'Every difficult task in the world becomes easy by your grace.',
    },
    {
      t: 192,
      section: 'Chaupai',
      devanagari: 'राम दुआरे तुम रखवारे। होत न आज्ञा बिनु पैसारे॥',
      transliteration: 'rāma duāre tuma rakhavāre, hota na ājñā binu paisāre',
      translation: 'You guard the door of Rama; none may enter without your leave.',
    },
    {
      t: 200,
      section: 'Chaupai',
      devanagari: 'सब सुख लहै तुम्हारी सरना। तुम रच्छक काहू को डर ना॥',
      transliteration: 'saba sukha lahai tumhārī saranā, tuma rachchhaka kāhū ko ḍara nā',
      translation: 'All joys are found in your refuge; with you as protector there is nothing to fear.',
    },
    {
      t: 208,
      section: 'Chaupai',
      devanagari: 'आपन तेज सम्हारो आपै। तीनों लोक हाँक तें काँपै॥',
      transliteration: 'āpana teja samhāro āpai, tīno loka hāka te kāpai',
      translation: 'You alone hold your own might; at your roar the three worlds tremble.',
    },
    {
      t: 216,
      section: 'Chaupai',
      devanagari: 'भूत पिशाच निकट नहिं आवै। महाबीर जब नाम सुनावै॥',
      transliteration: 'bhūta pishācha nikata nahi āvai, mahābīra jaba nāma sunāvai',
      translation: 'Ghosts and evil spirits dare not draw near when your name, O Mahavir, is spoken.',
    },
    {
      t: 224,
      section: 'Chaupai',
      devanagari: 'नासै रोग हरै सब पीरा। जपत निरंतर हनुमत बीरा॥',
      transliteration: 'nāsai roga harai saba pīrā, japata nirantara hanumata bīrā',
      translation: "Disease is destroyed and all pain removed by ceaseless repetition of brave Hanuman's name.",
    },
    {
      t: 232,
      section: 'Chaupai',
      devanagari: 'संकट तें हनुमान छुड़ावै। मन क्रम बचन ध्यान जो लावै॥',
      transliteration: 'sankata te hanumāna chhuṛāvai, mana krama bachana dhyāna jo lāvai',
      translation: 'Hanuman frees from distress all who hold him in thought, word and deed.',
    },
    {
      t: 240,
      section: 'Chaupai',
      devanagari: 'सब पर राम तपस्वी राजा। तिन के काज सकल तुम साजा॥',
      transliteration: 'saba para rāma tapasvī rājā, tina ke kāja sakala tuma sājā',
      translation: 'Rama the ascetic king reigns over all; you accomplish all his works.',
    },
    {
      t: 248,
      section: 'Chaupai',
      devanagari: 'और मनोरथ जो कोई लावै। सोइ अमित जीवन फल पावै॥',
      transliteration: 'aura manoratha jo koī lāvai, soi amita jīvana phala pāvai',
      translation: 'Whoever brings any heartfelt wish to you obtains its boundless fruit in life.',
    },
    {
      t: 256,
      section: 'Chaupai',
      devanagari: 'चारों जुग परताप तुम्हारा। है परसिद्ध जगत उजियारा॥',
      transliteration: 'chāro juga paratāpa tumhārā, hai parasiddha jagata ujiyārā',
      translation: 'Your glory blazes through all four ages, renowned and lighting up the world.',
    },
    {
      t: 264,
      section: 'Chaupai',
      devanagari: 'साधु संत के तुम रखवारे। असुर निकंदन राम दुलारे॥',
      transliteration: 'sādhu santa ke tuma rakhavāre, asura nikandana rāma dulāre',
      translation: 'Guardian of the saints and sages, destroyer of demons, beloved of Rama,',
    },
    {
      t: 272,
      section: 'Chaupai',
      devanagari: 'अष्ट सिद्धि नौ निधि के दाता। अस बर दीन्ह जानकी माता॥',
      transliteration: 'ashta siddhi nau nidhi ke dātā, asa bara dīnha jānakī mātā',
      translation: 'Giver of the eight powers and nine treasures — such a boon Mother Janaki granted you.',
    },
    {
      t: 280,
      section: 'Chaupai',
      devanagari: 'राम रसायन तुम्हरे पासा। सदा रहो रघुपति के दासा॥',
      transliteration: 'rāma rasāyana tumhare pāsā, sadā raho raghupati ke dāsā',
      translation: "The elixir of Rama's name is yours; may you ever remain his servant.",
    },
    {
      t: 288,
      section: 'Chaupai',
      devanagari: 'तुम्हरे भजन राम को पावै। जनम जनम के दुख बिसरावै॥',
      transliteration: 'tumhare bhajana rāma ko pāvai, janama janama ke dukha bisarāvai',
      translation: 'Through singing your praise one reaches Rama and forgets the sorrows of countless births.',
    },
    {
      t: 296,
      section: 'Chaupai',
      devanagari: 'अंत काल रघुबर पुर जाई। जहाँ जन्म हरि-भक्त कहाई॥',
      transliteration: 'anta kāla raghubara pura jāī, jahā janma hari-bhakta kahāī',
      translation: "At life's end one goes to Rama's abode, reborn ever after a devotee of Hari.",
    },
    {
      t: 304,
      section: 'Chaupai',
      devanagari: 'और देवता चित्त न धरई। हनुमत सेइ सर्ब सुख करई॥',
      transliteration: 'aura devatā chitta na dharaī, hanumata sei sarba sukha karaī',
      translation: 'Hold no other god in mind; serving Hanuman alone brings every joy.',
    },
    {
      t: 312,
      section: 'Chaupai',
      devanagari: 'संकट कटै मिटै सब पीरा। जो सुमिरै हनुमत बलबीरा॥',
      transliteration: 'sankata katai mitai saba pīrā, jo sumirai hanumata balabīrā',
      translation: 'All troubles are cut away and pain ends for whoever remembers mighty Hanuman.',
    },
    {
      t: 320,
      section: 'Chaupai',
      devanagari: 'जय जय जय हनुमान गोसाईं। कृपा करहु गुरुदेव की नाईं॥',
      transliteration: 'jaya jaya jaya hanumāna gosāī, kṛpā karahu gurudeva kī nāī',
      translation: 'Victory, victory, victory to Lord Hanuman! Grant your grace as a guru would.',
    },
    {
      t: 328,
      section: 'Chaupai',
      devanagari: 'जो सत बार पाठ कर कोई। छूटहि बंदि महा सुख होई॥',
      transliteration: 'jo sata bāra pātha kara koī, chhūtahi bandi mahā sukha hoī',
      translation: 'Whoever recites this a hundred times is freed from bondage and gains great bliss.',
    },
    {
      t: 336,
      section: 'Chaupai',
      devanagari: 'जो यह पढ़ै हनुमान चालीसा। होय सिद्धि साखी गौरीसा॥',
      transliteration: 'jo yaha paṛhai hanumāna chālīsā, hoya siddhi sākhī gaurīsā',
      translation: 'Whoever reads this Hanuman Chalisa attains perfection — Shiva himself bears witness.',
    },
    {
      t: 344,
      section: 'Chaupai',
      devanagari: 'तुलसीदास सदा हरि चेरा। कीजै नाथ हृदय महँ डेरा॥',
      transliteration: 'tulasīdāsa sadā hari cherā, kījai nātha hṛdaya maha ḍerā',
      translation: "Tulsidas, ever Hari's servant, prays: O Lord, make your home within my heart.",
    },
    {
      t: 352,
      section: 'Doha',
      devanagari: 'पवनतनय संकट हरन, मंगल मूरति रूप।',
      transliteration: 'pavana-tanaya sankata harana, mangala mūrati rūpa',
      translation: 'O son of the Wind, remover of distress, embodiment of auspiciousness,',
    },
    {
      t: 360,
      section: 'Doha',
      devanagari: 'राम लखन सीता सहित, हृदय बसहु सुर भूप॥',
      transliteration: 'rāma lakhana sītā sahita, hridaya basahu sura bhūpa',
      translation: 'dwell in my heart with Rama, Lakshmana and Sita, O king among the gods.',
    },
  ],
};

const omJaiJagdish: Track = {
  id: 'om-jai-jagdish-hare',
  title: 'Om Jai Jagdish Hare',
  devanagari: 'ॐ जय जगदीश हरे',
  kind: 'aarti',
  deityId: 'vishnu',
  language: 'hi',
  artist: 'Traditional · Shardha Ram Phillauri',
  duration: 72,
  audio: null,
  isFree: true,
  previewSeconds: 45,
  attribution: 'Pandit Shardha Ram Phillauri (1870) · public domain',
  tags: ['aarti', 'universal', 'evening'],
  lyrics: [
    {
      t: 0,
      section: 'Refrain',
      devanagari: 'ॐ जय जगदीश हरे, स्वामी जय जगदीश हरे।',
      transliteration: 'oṁ jaya jagadīsha hare, swāmī jaya jagadīsha hare',
      translation: 'Om, victory to the Lord of the universe, O master, victory to you.',
    },
    {
      t: 10,
      section: 'Refrain',
      devanagari: 'भक्त जनों के संकट, क्षण में दूर करे॥',
      transliteration: 'bhakta janon ke sankata, kshana men dūra kare',
      translation: 'You remove the troubles of your devotees in an instant.',
    },
    {
      t: 20,
      section: 'Verse 1',
      devanagari: 'जो ध्यावे फल पावे, दुख बिनसे मन का।',
      transliteration: 'jo dhyāve phala pāve, dukha binase mana kā',
      translation: 'Whoever meditates on you gains the fruit; the sorrow of the mind is destroyed.',
    },
    {
      t: 30,
      section: 'Verse 1',
      devanagari: 'सुख सम्पति घर आवे, कष्ट मिटे तन का॥',
      transliteration: 'sukha sampati ghara āve, kashta mite tana kā',
      translation: 'Happiness and prosperity come home, and bodily suffering is removed.',
    },
  ],
};

const gayatri: Track = {
  id: 'gayatri-mantra',
  title: 'Gayatri Mantra',
  devanagari: 'गायत्री मंत्र',
  kind: 'mantra',
  deityId: 'surya',
  language: 'sa',
  artist: 'Vedic · Rishi Vishvamitra',
  duration: 40,
  audio: null,
  isFree: true,
  attribution: 'Rig Veda 3.62.10 · public domain',
  tags: ['dawn', 'clarity', 'vedic'],
  lyrics: [
    {
      t: 0,
      devanagari: 'ॐ भूर्भुवः स्वः।',
      transliteration: 'oṁ bhūr bhuvaḥ svaḥ',
      translation: 'Om. The earth, the atmosphere, the heavens.',
      words: [
        { text: 'oṁ', t: 0 }, { text: 'bhūr', t: 2 }, { text: 'bhuvaḥ', t: 4 }, { text: 'svaḥ', t: 6 },
      ],
    },
    {
      t: 8,
      devanagari: 'तत्सवितुर्वरेण्यं।',
      transliteration: 'tat savitur vareṇyaṁ',
      translation: 'That adorable splendor of the divine Sun,',
      words: [{ text: 'tat', t: 0 }, { text: 'savitur', t: 2.5 }, { text: 'vareṇyaṁ', t: 5 }],
    },
    {
      t: 16,
      devanagari: 'भर्गो देवस्य धीमहि।',
      transliteration: 'bhargo devasya dhīmahi',
      translation: 'the radiant light of the deity, on which we meditate —',
      words: [{ text: 'bhargo', t: 0 }, { text: 'devasya', t: 2.5 }, { text: 'dhīmahi', t: 5 }],
    },
    {
      t: 24,
      devanagari: 'धियो यो नः प्रचोदयात्॥',
      transliteration: 'dhiyo yo naḥ prachodayāt',
      translation: 'may it illumine and inspire our understanding.',
      words: [
        { text: 'dhiyo', t: 0 }, { text: 'yo', t: 4 }, { text: 'naḥ', t: 8 }, { text: 'prachodayāt', t: 11 },
      ],
    },
  ],
};

const vakratunda: Track = {
  id: 'vakratunda-mahakaya',
  title: 'Vakratunda Mahakaya',
  devanagari: 'वक्रतुण्ड महाकाय',
  kind: 'mantra',
  deityId: 'ganesha',
  language: 'sa',
  artist: 'Traditional',
  duration: 24,
  audio: null,
  isFree: true,
  attribution: 'Ganesha dhyana shloka · public domain',
  tags: ['beginnings', 'obstacles'],
  lyrics: [
    {
      t: 0,
      devanagari: 'वक्रतुण्ड महाकाय सूर्यकोटि समप्रभ।',
      transliteration: 'vakratuṇḍa mahākāya sūryakoṭi samaprabha',
      translation: 'O curved-trunk, mighty-bodied one, radiant as ten million suns,',
      words: [
        { text: 'vakratuṇḍa', t: 0 }, { text: 'mahākāya', t: 3 }, { text: 'sūryakoṭi', t: 6 }, { text: 'samaprabha', t: 9 },
      ],
    },
    {
      t: 12,
      devanagari: 'निर्विघ्नं कुरु मे देव सर्वकार्येषु सर्वदा॥',
      transliteration: 'nirvighnaṁ kuru me deva sarva-kāryeṣu sarvadā',
      translation: 'make all my endeavors free of obstacles, O Lord, always.',
      words: [
        { text: 'nirvighnaṁ', t: 0 }, { text: 'kuru', t: 2 }, { text: 'me', t: 3.5 }, { text: 'deva', t: 5 }, { text: 'sarva-kāryeṣu', t: 7 }, { text: 'sarvadā', t: 10 },
      ],
    },
  ],
};

const mahaMantra: Track = {
  id: 'hare-krishna-maha-mantra',
  title: 'Hare Krishna Maha Mantra',
  devanagari: 'हरे कृष्ण महामंत्र',
  kind: 'mantra',
  deityId: 'krishna',
  language: 'sa',
  artist: 'Traditional',
  duration: 32,
  audio: null,
  isFree: true,
  attribution: 'Kali-Santarana Upanishad · public domain',
  tags: ['kirtan', 'japa', 'joy'],
  lyrics: [
    {
      t: 0,
      devanagari: 'हरे कृष्ण हरे कृष्ण, कृष्ण कृष्ण हरे हरे।',
      transliteration: 'hare kṛṣṇa hare kṛṣṇa, kṛṣṇa kṛṣṇa hare hare',
      translation: 'O energy of the Lord, O all-attractive Lord, please engage me in your service.',
      words: [
        { text: 'hare', t: 0 }, { text: 'kṛṣṇa', t: 2 }, { text: 'hare', t: 4 }, { text: 'kṛṣṇa', t: 6 },
        { text: 'kṛṣṇa', t: 8 }, { text: 'kṛṣṇa', t: 10 }, { text: 'hare', t: 12 }, { text: 'hare', t: 14 },
      ],
    },
    {
      t: 16,
      devanagari: 'हरे राम हरे राम, राम राम हरे हरे॥',
      transliteration: 'hare rāma hare rāma, rāma rāma hare hare',
      translation: 'O energy of the Lord, O reservoir of joy, please engage me in your service.',
      words: [
        { text: 'hare', t: 0 }, { text: 'rāma', t: 2 }, { text: 'hare', t: 4 }, { text: 'rāma', t: 6 },
        { text: 'rāma', t: 8 }, { text: 'rāma', t: 10 }, { text: 'hare', t: 12 }, { text: 'hare', t: 14 },
      ],
    },
  ],
};

const omNamahShivaya: Track = {
  id: 'om-namah-shivaya',
  title: 'Om Namah Shivaya',
  devanagari: 'ॐ नमः शिवाय',
  kind: 'mantra',
  deityId: 'shiva',
  language: 'sa',
  artist: 'Traditional',
  duration: 30,
  audio: null,
  isFree: true,
  attribution: 'Panchakshara mantra, Yajurveda · public domain',
  tags: ['monday', 'stillness', 'japa'],
  lyrics: [
    {
      t: 0,
      devanagari: 'ॐ नमः शिवाय।',
      transliteration: 'oṁ namaḥ śivāya',
      translation: 'Om, I bow to Shiva — the auspicious inner Self.',
      words: [{ text: 'oṁ', t: 0 }, { text: 'namaḥ', t: 3 }, { text: 'śivāya', t: 6 }],
    },
    {
      t: 10,
      devanagari: 'ॐ नमः शिवाय।',
      transliteration: 'oṁ namaḥ śivāya',
      translation: 'Om, I bow to Shiva — the auspicious inner Self.',
      words: [{ text: 'oṁ', t: 0 }, { text: 'namaḥ', t: 3 }, { text: 'śivāya', t: 6 }],
    },
    {
      t: 20,
      devanagari: 'ॐ नमः शिवाय।',
      transliteration: 'oṁ namaḥ śivāya',
      translation: 'Om, I bow to Shiva — the auspicious inner Self.',
      words: [{ text: 'oṁ', t: 0 }, { text: 'namaḥ', t: 3 }, { text: 'śivāya', t: 6 }],
    },
  ],
};

const morningMeditation: Track = {
  id: 'morning-stillness',
  title: 'Morning Stillness',
  kind: 'meditation',
  deityId: 'shiva',
  language: 'en',
  artist: 'Diya',
  duration: 60,
  audio: null,
  isFree: false,
  previewSeconds: 20,
  attribution: 'Original guided practice',
  tags: ['meditation', 'breath', 'morning'],
  lyrics: [
    { t: 0, transliteration: 'Settle comfortably, spine easy, eyes softly closed.', translation: 'Arrive.' },
    { t: 12, transliteration: 'Breathe in for four… and release for six.', translation: 'Lengthen the exhale.' },
    { t: 28, transliteration: 'Silently offer: Om Namah Shivaya.', translation: 'Let the mantra arise on its own.' },
    { t: 44, transliteration: 'Rest in the stillness between two breaths.', translation: 'This is the temple within.' },
  ],
};

export const TRACKS: Track[] = [
  hanumanChalisa,
  omJaiJagdish,
  gayatri,
  vakratunda,
  mahaMantra,
  omNamahShivaya,
  morningMeditation,
];
