import type { Track } from '../types';

/**
 * Additional aartis, mantras and bhajans across the pantheon, so the library,
 * journeys and deity pages have real material. Same rules as the core seed:
 * `audio` is null (follow-along), text is traditional/public-domain, and
 * translations are plain-English renderings pending scholarly review.
 */
export const EXTRA_TRACKS: Track[] = [
  {
    id: 'jai-ganesh-deva',
    title: 'Jai Ganesh Deva',
    devanagari: 'जय गणेश देवा',
    kind: 'aarti',
    deityId: 'ganesha',
    language: 'hi',
    artist: 'Traditional',
    duration: 48,
    audio: null,
    isFree: true,
    previewSeconds: 30,
    attribution: 'Traditional aarti · public domain',
    tags: ['aarti', 'beginnings', 'wednesday'],
    lyrics: [
      { t: 0, section: 'Refrain', devanagari: 'जय गणेश जय गणेश जय गणेश देवा।', transliteration: 'jaya gaṇesha jaya gaṇesha jaya gaṇesha devā', translation: 'Victory to Lord Ganesha, again and again.' },
      { t: 10, section: 'Refrain', devanagari: 'माता जाकी पार्वती पिता महादेवा॥', transliteration: 'mātā jākī pārvatī pitā mahādevā', translation: 'Whose mother is Parvati and whose father is Mahadeva.' },
      { t: 22, devanagari: 'एकदंत दयावंत चार भुजाधारी।', transliteration: 'ekadanta dayāvanta chāra bhujā dhārī', translation: 'Single-tusked and compassionate, bearing four arms,' },
      { t: 34, devanagari: 'माथे सिंदूर सोहे मूसे की सवारी॥', transliteration: 'māthe sindūra sohe mūse kī savārī', translation: 'vermilion gracing your brow, riding upon the mouse.' },
    ],
  },
  {
    id: 'om-jai-lakshmi-mata',
    title: 'Om Jai Lakshmi Mata',
    devanagari: 'ॐ जय लक्ष्मी माता',
    kind: 'aarti',
    deityId: 'lakshmi',
    language: 'hi',
    artist: 'Traditional',
    duration: 44,
    audio: null,
    isFree: true,
    attribution: 'Traditional aarti · public domain',
    tags: ['aarti', 'friday', 'abundance', 'diwali'],
    lyrics: [
      { t: 0, section: 'Refrain', devanagari: 'ॐ जय लक्ष्मी माता, मैया जय लक्ष्मी माता।', transliteration: 'oṁ jaya lakshmī mātā, maiyā jaya lakshmī mātā', translation: 'Om, victory to Mother Lakshmi, hail to you, Mother.' },
      { t: 12, section: 'Refrain', devanagari: 'तुमको निशदिन सेवत, हर विष्णु विधाता॥', transliteration: 'tumako niśadina sevata, hara vishṇu vidhātā', translation: 'Shiva, Vishnu and Brahma serve you day and night.' },
      { t: 26, devanagari: 'उमा रमा ब्रह्माणी, तुम ही जग माता।', transliteration: 'umā ramā brahmāṇī, tuma hī jaga mātā', translation: 'As Uma, Rama and Brahmani, you are the mother of the world.' },
      { t: 36, devanagari: 'सूर्य चंद्रमा ध्यावत, नारद ऋषि गाता॥', transliteration: 'sūrya chandramā dhyāvata, nārada ṛṣi gātā', translation: 'The sun and moon meditate on you; sage Narada sings your praise.' },
    ],
  },
  {
    id: 'ambe-tu-hai-jagdambe',
    title: 'Ambe Tu Hai Jagdambe',
    devanagari: 'अम्बे तू है जगदम्बे',
    kind: 'aarti',
    deityId: 'durga',
    language: 'hi',
    artist: 'Traditional',
    duration: 46,
    audio: null,
    isFree: true,
    attribution: 'Traditional aarti · public domain',
    tags: ['aarti', 'navratri', 'shakti'],
    lyrics: [
      { t: 0, section: 'Refrain', devanagari: 'अम्बे तू है जगदम्बे काली, जय दुर्गे खप्पर वाली।', transliteration: 'ambe tū hai jagadambe kālī, jaya durge khappara vālī', translation: 'O Amba, you are the Mother of the world, Kali; victory to Durga who bears the bowl.' },
      { t: 14, section: 'Refrain', devanagari: 'तेरे ही गुण गावें भारती, ओ मैया हम सब उतारें आरती॥', transliteration: 'tere hī guṇa gāven bhāratī, o maiyā hama saba utāren āratī', translation: 'We sing only your glories, Mother, and offer this aarti to you.' },
      { t: 30, devanagari: 'तेरे भक्त जनों पर माता, भीर पड़ी है भारी।', transliteration: 'tere bhakta janon para mātā, bhīra paṛī hai bhārī', translation: 'O Mother, when great trouble falls upon your devotees,' },
      { t: 40, devanagari: 'दानव दल पर टूट पड़ो माँ, करके सिंह सवारी॥', transliteration: 'dānava dala para ṭūṭa paṛo māṁ, karake siṁha savārī', translation: 'fall upon the hordes of demons, riding your lion.' },
    ],
  },
  {
    id: 'om-jai-shiv-omkara',
    title: 'Om Jai Shiv Omkara',
    devanagari: 'ॐ जय शिव ओंकारा',
    kind: 'aarti',
    deityId: 'shiva',
    language: 'hi',
    artist: 'Traditional',
    duration: 42,
    audio: null,
    isFree: false,
    previewSeconds: 25,
    attribution: 'Traditional aarti · public domain',
    tags: ['aarti', 'monday', 'shivaratri'],
    lyrics: [
      { t: 0, section: 'Refrain', devanagari: 'ॐ जय शिव ओंकारा, स्वामी जय शिव ओंकारा।', transliteration: 'oṁ jaya śiva oṁkārā, swāmī jaya śiva oṁkārā', translation: 'Om, victory to Shiva, the primordial sound Omkara.' },
      { t: 12, section: 'Refrain', devanagari: 'ब्रह्मा विष्णु सदाशिव, अर्द्धांगी धारा॥', transliteration: 'brahmā vishṇu sadāśiva, arddhāṅgī dhārā', translation: 'Brahma, Vishnu and eternal Shiva — you hold the half-feminine form.' },
      { t: 26, devanagari: 'एकानन चतुरानन पञ्चानन राजे।', transliteration: 'ekānana chaturānana pañchānana rāje', translation: 'One-faced, four-faced and five-faced, you reign,' },
      { t: 34, devanagari: 'हंसासन गरुड़ासन वृषवाहन साजे॥', transliteration: 'haṁsāsana garuḍāsana vṛṣavāhana sāje', translation: 'adorned on swan, eagle and the bull as your mount.' },
    ],
  },
  {
    id: 'saraswati-vandana',
    title: 'Saraswati Vandana',
    devanagari: 'सरस्वती वंदना',
    kind: 'stotra',
    deityId: 'saraswati',
    language: 'sa',
    artist: 'Traditional',
    duration: 36,
    audio: null,
    isFree: false,
    previewSeconds: 20,
    attribution: 'Traditional dhyana shloka · public domain',
    tags: ['knowledge', 'students', 'vasant-panchami'],
    lyrics: [
      { t: 0, devanagari: 'या कुन्देन्दुतुषारहारधवला या शुभ्रवस्त्रावृता।', transliteration: 'yā kundendu-tuṣāra-hāra-dhavalā yā śubhra-vastrāvṛtā', translation: 'She who is white as jasmine, the moon and snow, robed in pure white,' },
      { t: 12, devanagari: 'या वीणावरदण्डमण्डितकरा या श्वेतपद्मासना॥', transliteration: 'yā vīṇā-vara-daṇḍa-maṇḍita-karā yā śveta-padmāsanā', translation: 'whose hands are graced by the veena, seated upon the white lotus —' },
      { t: 24, devanagari: 'सा मां पातु सरस्वती भगवती निःशेषजाड्यापहा॥', transliteration: 'sā māṁ pātu sarasvatī bhagavatī niḥśeṣa-jāḍyāpahā', translation: 'may that Goddess Saraswati, remover of all dullness, protect me.' },
    ],
  },
  {
    id: 'govind-bolo',
    title: 'Govind Bolo Hari Gopal Bolo',
    devanagari: 'गोविन्द बोलो',
    kind: 'bhajan',
    deityId: 'krishna',
    language: 'hi',
    artist: 'Traditional',
    duration: 40,
    audio: null,
    isFree: true,
    attribution: 'Traditional bhajan · public domain',
    tags: ['kirtan', 'joy', 'janmashtami'],
    lyrics: [
      { t: 0, devanagari: 'गोविन्द बोलो हरि गोपाल बोलो।', transliteration: 'govinda bolo hari gopāla bolo', translation: 'Sing the names: Govinda, Hari, Gopala!' },
      { t: 12, devanagari: 'राधा रमण हरि गोविन्द बोलो॥', transliteration: 'rādhā ramaṇa hari govinda bolo', translation: 'Beloved of Radha, Hari — sing Govinda!' },
      { t: 24, devanagari: 'गोविन्द बोलो हरि गोपाल बोलो।', transliteration: 'govinda bolo hari gopāla bolo', translation: 'Sing the names: Govinda, Hari, Gopala!' },
    ],
  },
  {
    id: 'durga-chalisa',
    title: 'Durga Chalisa',
    devanagari: 'दुर्गा चालीसा',
    kind: 'chalisa',
    deityId: 'durga',
    language: 'hi',
    artist: 'Traditional',
    duration: 86,
    audio: null,
    isFree: true,
    previewSeconds: 30,
    attribution: 'Traditional chalisa · public domain',
    tags: ['navratri', 'shakti', 'protection'],
    lyrics: [
      { t: 0, section: 'Doha', devanagari: 'नमो नमो दुर्गे सुख करनी। नमो नमो अम्बे दुख हरनी॥', transliteration: 'namo namo durge sukha karanī, namo namo ambe dukha haranī', translation: 'Salutations, O Durga, giver of joy; salutations, O Amba, remover of sorrow.' },
      { t: 12, devanagari: 'निराकार है ज्योति तुम्हारी। तिहूँ लोक फैली उजियारी॥', transliteration: 'nirākāra hai jyoti tumhārī, tihūn loka phailī ujiyārī', translation: 'Formless is your light, spreading radiance through the three worlds.' },
      { t: 26, devanagari: 'शशि ललाट मुख महाविशाला। नेत्र लाल भृकुटी विकराला॥', transliteration: 'śaśi lalāṭa mukha mahā-viśālā, netra lāla bhṛkuṭī vikarālā', translation: 'The moon upon your brow, your face vast; eyes red, your gaze terrible to evil.' },
      { t: 38, devanagari: 'रूप मातु को अधिक सुहावे। दरश करत जन अति सुख पावे॥', transliteration: 'rūpa mātu ko adhika suhāve, darasha karata jana ati sukha pāve', translation: 'Your form, O Mother, is exceedingly lovely; beholding it, devotees gain great joy.' },
      { t: 50, devanagari: 'तुम संसार शक्ति लय कीना। पालन हेतु अन्न धन दीना॥', transliteration: 'tuma sansāra shakti laya kīnā, pālana hetu anna dhana dīnā', translation: 'You hold the power of all creation; for our sustenance you grant food and wealth.' },
      { t: 62, devanagari: 'अन्नपूर्णा हुई जग पाला। तुम ही आदि सुन्दरी बाला॥', transliteration: 'annapūrṇā huī jaga pālā, tuma hī ādi sundarī bālā', translation: 'As Annapurna you nourish the world; you are the primordial, ever-youthful beauty.' },
      { t: 74, devanagari: 'प्रलयकाल सब नाशन हारी। तुम गौरी शिवशंकर प्यारी॥', transliteration: 'pralayakāla saba nāshana hārī, tuma gaurī shivashankara pyārī', translation: 'At the dissolution of all things you are the destroyer; you are Gauri, beloved of Shiva.' },
    ],
  },
  {
    id: 'shiv-chalisa',
    title: 'Shiv Chalisa',
    devanagari: 'शिव चालीसा',
    kind: 'chalisa',
    deityId: 'shiva',
    language: 'hi',
    artist: 'Traditional · Ayodhyadas',
    duration: 84,
    audio: null,
    isFree: false,
    previewSeconds: 25,
    attribution: 'Ayodhyadas · public domain',
    tags: ['monday', 'shivaratri'],
    lyrics: [
      { t: 0, section: 'Doha', devanagari: 'जय गणेश गिरिजा सुवन, मंगल मूल सुजान।', transliteration: 'jaya gaṇeśa girijā suvana, maṅgala mūla sujāna', translation: 'Victory to Ganesha, son of Parvati, wise root of all auspiciousness.' },
      { t: 12, devanagari: 'कहत अयोध्यादास तुम, देहु अभय वरदान॥', transliteration: 'kahata ayodhyādāsa tuma, dehu abhaya varadāna', translation: 'Ayodhyadas prays: grant me the boon of fearlessness.' },
      { t: 24, section: 'Chaupai', devanagari: 'जय गिरिजापति दीनदयाला। सदा करत सन्तन प्रतिपाला॥', transliteration: 'jaya girijāpati dīnadayālā, sadā karata santana pratipālā', translation: 'Victory to the Lord of Parvati, kind to the humble, ever protector of the saints.' },
      { t: 36, section: 'Chaupai', devanagari: 'भाल चन्द्रमा सोहत नीके। कानन कुण्डल नागफनी के॥', transliteration: 'bhāla chandramā sohata nīke, kānana kuṇḍala nāgaphanī ke', translation: 'The moon graces your brow; serpent-hood rings adorn your ears.' },
      { t: 48, section: 'Chaupai', devanagari: 'अंग गौर शिर गंग बहाये। मुण्डमाल तन क्षार लगाये॥', transliteration: 'anga gaura shira ganga bahāye, muṇḍamāla tana kshāra lagāye', translation: 'Fair of limb, the Ganga streaming from your head; garlanded with skulls, your body smeared with ash.' },
      { t: 60, section: 'Chaupai', devanagari: 'वस्त्र खाल बाघम्बर सोहे। छवि को देख नाग मन मोहे॥', transliteration: 'vastra khāla bāghambara sohe, chhavi ko dekha nāga mana mohe', translation: 'Clad in a tiger’s hide; even serpents are charmed beholding your form.' },
      { t: 72, section: 'Chaupai', devanagari: 'मैना मातु की हवे दुलारी। बाम अंग सोहत छवि न्यारी॥', transliteration: 'mainā mātu kī have dulārī, bāma anga sohata chhavi nyārī', translation: 'Dear to Mother Maina; Parvati graces your left side in matchless beauty.' },
    ],
  },
  {
    id: 'kali-mantra',
    title: 'Kali Mantra',
    devanagari: 'काली मंत्र',
    kind: 'mantra',
    deityId: 'kali',
    language: 'sa',
    artist: 'Traditional',
    duration: 24,
    audio: null,
    isFree: true,
    attribution: 'Beeja mantra · public domain',
    tags: ['shakti', 'fearlessness', 'japa'],
    lyrics: [
      { t: 0, devanagari: 'ॐ क्रीं कालिकायै नमः।', transliteration: 'oṁ krīṁ kālikāyai namaḥ', translation: 'Om, salutations to Kali, who dissolves fear and ego.' },
      { t: 12, devanagari: 'ॐ क्रीं कालिकायै नमः।', transliteration: 'oṁ krīṁ kālikāyai namaḥ', translation: 'Om, salutations to Kali, who dissolves fear and ego.' },
    ],
  },
  {
    id: 'om-saravanabhava',
    title: 'Om Saravanabhava',
    devanagari: 'ॐ शरवणभव',
    kind: 'mantra',
    deityId: 'kartikeya',
    language: 'sa',
    artist: 'Traditional',
    duration: 24,
    audio: null,
    isFree: true,
    attribution: 'Shadakshara mantra · public domain',
    tags: ['murugan', 'courage', 'tuesday'],
    lyrics: [
      { t: 0, devanagari: 'ॐ शरवणभव।', transliteration: 'oṁ śaravaṇa-bhava', translation: 'Om, salutations to Murugan, born amid the reeds.' },
      { t: 12, devanagari: 'ॐ शरवणभव।', transliteration: 'oṁ śaravaṇa-bhava', translation: 'Om, salutations to Murugan, born amid the reeds.' },
    ],
  },
  {
    id: 'om-jai-gange',
    title: 'Om Jai Gange Mata',
    devanagari: 'ॐ जय गंगे माता',
    kind: 'aarti',
    deityId: 'ganga',
    language: 'hi',
    artist: 'Traditional',
    duration: 36,
    audio: null,
    isFree: true,
    attribution: 'Traditional aarti · public domain',
    tags: ['aarti', 'purity', 'river'],
    lyrics: [
      { t: 0, section: 'Refrain', devanagari: 'ॐ जय गंगे माता, मैया जय गंगे माता।', transliteration: 'oṁ jaya gaṅge mātā, maiyā jaya gaṅge mātā', translation: 'Om, victory to Mother Ganga, hail to you, Mother.' },
      { t: 14, devanagari: 'जो नर तुमको ध्याता, मनवांछित फल पाता॥', transliteration: 'jo nara tumako dhyātā, manavāñchita phala pātā', translation: 'Whoever meditates on you attains the heart’s desire.' },
    ],
  },
];
