import type { IconName } from '@/components/ui';

/**
 * Ambient soundscapes for darshan & meditation. This is an audio seam: like the
 * tracks, the loops aren't bundled yet. Selecting one sets the mood visually and
 * is wired to drop in a looping `expo-audio` source per id when assets are ready.
 */
export interface Ambience {
  id: string;
  label: string;
  icon: IconName;
  /**
   * Looping audio source (a remote URL to a seamless loop). Undefined = silent
   * until a loop asset is added — the engine + picker are already wired, so
   * setting this is all that's needed to make an ambience play.
   */
  uri?: string;
}

/**
 * Where the loop assets live. Generated by `scripts/make-ambience.mjs` and
 * hosted in the repo (served via the GitHub raw URL, like the demo recitation).
 * Override with EXPO_PUBLIC_AMBIENCE_BASE to serve from your own CDN.
 */
const AMBIENCE_BASE =
  process.env.EXPO_PUBLIC_AMBIENCE_BASE ??
  'https://raw.githubusercontent.com/DileepJexpert/Diya-Daily-Hindu-Prayer/main/public/audio/ambience';

export const AMBIENCE: Ambience[] = [
  { id: 'none', label: 'Silence', icon: 'remove-circle-outline' },
  { id: 'bells', label: 'Temple bells', icon: 'notifications-outline', uri: `${AMBIENCE_BASE}/temple-bells.wav` },
  { id: 'river', label: 'River', icon: 'water-outline', uri: `${AMBIENCE_BASE}/river.wav` },
  { id: 'om', label: 'Om drone', icon: 'radio-outline', uri: `${AMBIENCE_BASE}/om-drone.wav` },
  { id: 'rain', label: 'Rain', icon: 'rainy-outline', uri: `${AMBIENCE_BASE}/rain.wav` },
];
